apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Chart.Name}}"
  labels:
    app: "{{.Chart.Name}}-{{.Chart.Version}}-{{.Chart.AppVersion}}"
spec:
  selector:
    matchLabels:
      app: "{{.Chart.Name}}-{{.Chart.Version}}-{{.Chart.AppVersion}}"
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{.Chart.Name}}-{{.Chart.Version}}-{{.Chart.AppVersion}}"
    spec:
      containers:
      - name: "{{.Chart.Name}}"
        image: "{{.Chart.Name}}:{{.Chart.AppVersion}}"
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: {{ .Values.ports.api }}
        - name: grpc-non-tls
          containerPort: {{ .Values.ports.grpc.nonTls }}
        - name: grpc-tls
          containerPort: {{ .Values.ports.grpc.tls }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.ports.api }}
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command:
            - cat
            - virtualservice.started
          initialDelaySeconds: 20
        resources:
          limits:
            memory: 256Mi
            cpu: 1.0

