#infoblox image pull secret
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6CnsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoKewogICJ1c2VybmFtZSI6InByYWthc2hrYiIsCiAgInBhc3N3b3JkIjoiM2NjYmUtNGFhZi00ZWYzLThjOGMtNzY4YzU0NWFiNGJkIiwKICAiZW1haWwiOiJwa2JAaW5mb2Jsb3guY29tIiwKICAiYXV0aCI6ImNISmhhMkZ6YUd0aU9qTmpZMkpsTmpFNUxUUmhZV1l0TkdWbU15MDRZemhqTFRjMk9HTTFORFZoWWpSaVpBPT0iCiAgfQp9Cn0= 
kind: Secret
metadata:
  name: infobloxpkbkey
  namespace: pkb
type: kubernetes.io/dockerconfigjson
---

#create service account for namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trafficparrot
  namespace: pkb
imagePullSecrets:
- name: infobloxpkbkey
---


